import { ROUTES } from "../utils/constants";

const rules = {
	admin: [
		ROUTES.HOME,
		ROUTES.APPOINTMENTS,
		ROUTES.DOCTORS,
		ROUTES.ABOUT,
		ROUTES.CONTACT,
		ROUTES.PROFILE,
	],
	doctor: [
		ROUTES.HOME,
		ROUTES.APPOINTMENTS,
		ROUTES.ABOUT,
		ROUTES.CONTACT,
		ROUTES.PROFILE,
	],
	user: [
		ROUTES.HOME,
		ROUTES.APPOINTMENTS,
		ROUTES.ABOUT,
		ROUTES.CONTACT,
		ROUTES.PROFILE,
	],
};

export default rules;
