import { ROUTES } from "../utils/constants";

const rules = {
	admin: [
		ROUTES.ADMIN,
		ROUTES.DOCTOR,
		ROUTES.USER,
		ROUTES.EMPLOYEE,
		ROUTES.PATIENT,
		ROUTES.PATIENT_LIST,
		ROUTES.APPOINTMENT,
		ROUTES.ACCOUNT,
		ROUTES.PROFILE,
		ROUTES.SETTINGS,
	],
	doctor: [
		ROUTES.DOCTOR,
		ROUTES.PATIENT,
		ROUTES.PATIENT_LIST,
		ROUTES.ACCOUNT,
		ROUTES.PROFILE,
		ROUTES.SETTINGS,
		ROUTES.APPOINTMENT,
	],
	user: [
		ROUTES.HOME,
		ROUTES.CONTACT,
		ROUTES.ACCOUNT,
		ROUTES.PROFILE,
		ROUTES.SETTINGS,
	],
};

export default rules;
